### ISSUE TITLE
Set up process for individual servers in README

### ISSUE THREAD

**Issue by tintindas** [Ashutosh00710/github-readme-activity-graph#23]
I think your activity graph is a really nice addition to anyone's profile readme. 

**Problem**
As the project grows in popularity your server maybe unable to handle the number of requests being made. 

**Proposed Solution**
You should get ahead of the problem by adding a set up process to the README for users to set up their own heroku instances to make requests to.

**Comment by Kshitij978** [comment]
Thanks, @tintindas for the appreciation and for opening this issue. 😄

This addition will definitely improve the quality of the documentation. Do you want to add it yourself or you want us to do so?

**Comment by tintindas** [comment]
I took a look at the repo and I don't think I could write a set up guide without knowing the environment variables being consumed by the project, if any.

Specifically, the **http://github-calendar.herokuapp.com/commits/last/${userId}** route looks like it consumes some kind of github authorisation token if I am not mistaken. 

Also, the mentioned route can be accessed by anyone even though its purpose is internal. 

This is the response when I query with my own username. I do not believe it is exposing sensitive information at the moment.

![image](https://user-images.githubusercontent.com/47525983/105490536-ee906b00-5cda-11eb-923f-a60f9efe9ab7.png)

**Comment by Ashutosh00710** [comment]
> Specifically, the http://github-calendar.herokuapp.com/commits/last/${userId} route looks like it consumes some kind of github authorisation token if I am not mistaken.

No, @tintindas there is no authorization token is required to fetch the user's contributions. Because, according to me, currently there is no way to get a user's everyday contributions using GitHub API, that's why we are using this URL.

`http://github-calendar.herokuapp.com/commits/last/${userId}` is fetching the user's contributions through some kind of html parsing. 

[Source of the URL](https://github.com/KaDw/github-calendar-api)

**Comment by tintindas** [comment]
Oh! That makes so much more sense. I misunderstood the code. Sure, I'll go ahead and write the documentation if it does not require any env variables :)

**Comment by Ashutosh00710** [comment]
Great @tintindas, go ahead. 😅

**Comment by Ashutosh00710** [comment]
Hey @tintindas, Sorry for the inconvenience. I unassigned you from the issue because I think I got the expected (user's contribution per day) response from GitHub API. If that's the case, it will include the environment variable.

I am keeping this issue open. Just hold for 1 or 2 days, until I am trying. If it's not going to work, I will let you know and reassign you the issue.

PS: What a lucky day as I was searching for the fix from the starting of the project but I couldn't find any. I dug a lot today fortunately I think I got it. 😲✨

**Comment by Ashutosh00710** [comment]
Hey @tintindas, Sorry for the inconvenience. I unassigned you from the issue because I think I got the expected (user's contribution per day) response from GitHub API. If that's the case, it will include the environment variable.

I am keeping this issue open. Just hold for 1 or 2 days, until I am trying. I will let you know and reassign you the issue.

PS: What a lucky day as I was searching for the fix from the starting of the project but I couldn't find any. I dug a lot today and fortunately I think I got it. 😲✨

**Comment by Ashutosh00710** [comment]
Issue #26 closed with commit number 140. Integrated GitHub GraphQl API. Now one environment variable **TOKEN** is added.

**Comment by Ashutosh00710** [comment]
Issue #26 closed with commit number 140. Integrated GitHub GraphQl API. Now one environment variable **TOKEN** is added.
We are updating **How To Contribute** section of CONTRIBUTING.md

**Comment by Ashutosh00710** [comment]
Hey @tintindas, I am reassigning this issue to you.

**Comment by tintindas** [comment]
@Ashutosh00710 great!!! 👍
