### ISSUE TITLE
Bug : Username is "null" in my case

### ISSUE THREAD

**Issue by junnei** [Ashutosh00710/github-readme-activity-graph#77]
**Describe the bug**
As I get graph from server, it gives me an error that my username is always "null".

**To Reproduce**
In my case,
URL : https://activity-graph.herokuapp.com/graph?username=junnei

**Expected behavior**
Just see an activity graph

**Screenshots**

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/41983244/125540368-ab50fa11-26e6-4bad-8b2d-abf965fc87cf.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser : safari
 - Version : 14.03

**Comment by Ashutosh00710** [comment]
The graph is fetching your Github name (not GitHub username) and you haven't set your name on GitHub that's why it is showing null.

There is a feature you can use:
Pass an argument `custom_title` or if you like any title from below, just copy the code and paste it on your markdown.

```MD
![Seongjun Jang Contribution Graph](https://activity-graph.herokuapp.com/graph?username=junnei&theme=react-dark&custom_title=Seongjun%20Jang%27s%20Contribution%20Graph)
```

It will look like ⬇

![Seongjun Jang Contribution Graph](https://activity-graph.herokuapp.com/graph?username=junnei&theme=react-dark&custom_title=Seongjun%20Jang%27s%20Contribution%20Graph)

**OR**

```MD
![Seongjun Jang Contribution Graph](https://activity-graph.herokuapp.com/graph?username=junnei&theme=react-dark&custom_title=junnei%27s%20Contribution%20Graph)
```

It will look like ⬇

![Seongjun Jang Contribution Graph](https://activity-graph.herokuapp.com/graph?username=junnei&theme=react-dark&custom_title=junnei%27s%20Contribution%20Graph)

**Comment by Ashutosh00710** [comment]
closing this issue with e949cdaba16b4f6c243141c8bad09ff66c5e51c2
