### ISSUE TITLE
BUG: Contribution counts are not aligned properly

### ISSUE THREAD

**Issue by DenverCoder1** [Ashutosh00710/github-readme-activity-graph#85]
**Describe the bug**
Dates are not aligned properly with contribution counts. Only the last 25 days of contributions are displayed but the last 31 days are displayed on the axis.

**To Reproduce**
Started very recently (past day or so)

**Expected behavior**
There should be commits for the past month aligned with the days for those contribution counts.

**Screenshots**
![image](https://user-images.githubusercontent.com/20955511/135730672-f5770f09-e42d-4be5-a389-cbd8733940c3.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Brave
 - Version 1.30.86 Chromium: 94.0.4606.61 (Official Build) (64-bit)

**Comment by DenverCoder1** [comment]
Is the deployment up-to-date?

I tried running the latest version of the code locally and it looks alright.

The dates do not appear next to the commits though.

![image](https://user-images.githubusercontent.com/20955511/135732470-f2ae2eec-c1d4-4d56-8bf4-b5a7c7ca875b.png)

**Comment by Ashutosh00710** [comment]
> Is the deployment up-to-date?

@DenverCoder1 Yes it is. But the branch that is available in production, is [this](https://github.com/Ashutosh00710/github-readme-activity-graph/tree/dates-feature).

- I've visited your profile and found that the graph is aligned correctly (I hope it is now correct at your end also) but I got why that happened. 
- If I am not wrong, it is because of the difference in the timezone between the hosted server and GitHub API. And due to this difference, [these](https://github.com/Ashutosh00710/github-readme-activity-graph/blob/b2fbea81683df3edc7965099cb0c6b7d06d1a27d/src/fetcher.ts#L88) (in [**`fetchContributions`**](https://github.com/Ashutosh00710/github-readme-activity-graph/blob/b2fbea81683df3edc7965099cb0c6b7d06d1a27d/src/fetcher.ts#L72)) calculations are going wrong.

I am still investigating the core of the issue. But the above-mentioned points are, what I found so far.

**Comment by Ashutosh00710** [comment]
ba8d804 will fix the issue.

**Comment by DenverCoder1** [comment]
It's definitely better. It seems like all of the contributions are a day behind though.

![image](https://user-images.githubusercontent.com/20955511/135930131-3c09da97-78e9-4e2b-9105-e906c2231114.png)

![image](https://user-images.githubusercontent.com/20955511/135930070-4078f066-9a03-4d5f-b8d5-6caa8a944ca7.png)

![image](https://user-images.githubusercontent.com/20955511/135930075-bb4a2cdd-ce88-4eba-a74b-0c21fb625d93.png)

**Comment by Ashutosh00710** [comment]
> It seems like all of the contributions are a day behind though. 

Yes, **the timezone issue**. I think I have to look for some other solution.
